builds:
- binary: chippy
  env:
  - GO111MODULE=
  - GOARCH=amd64
  - GOBIN=
  - GOCACHE=/Users/bradford/Library/Caches/go-build
  - GOENV=/Users/bradford/Library/Application Support/go/env
  - GOEXE=
  - GOFLAGS=
  - GOHOSTARCH=amd64
  - GOHOSTOS=darwin
  - GOINSECURE=
  - GONOPROXY=
  - GONOSUMDB=
  - GOOS=darwin
  - GOPATH=/Users/bradford/workspace/go
  - GOPRIVATE=
  - GOPROXY=https://proxy.golang.org,direct
  - GOROOT=/usr/local/go
  - GOSUMDB=sum.golang.org
  - GOTMPDIR=
  - GOTOOLDIR=/usr/local/go/pkg/tool/darwin_amd64
  - GCCGO=gccgo
  - AR=ar
  - CC=clang
  - CXX=clang++
  - CGO_ENABLED=1
  - GOMOD=/Users/bradford/workspace/go/src/github.com/bradford-hamilton/chippy/go.mod
  - CGO_CFLAGS=-g -O2
  - CGO_CPPFLAGS=
  - CGO_CXXFLAGS=-g -O2
  - CGO_FFLAGS=-g -O2
  - CGO_LDFLAGS=-g -O2
  - PKG_CONFIG=pkg-config
  - GOGCCFLAGS=-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4x/xdx4db1j5r56wbt1kj_rnsf00000gn/T/go-build306166820=/tmp/go-build -gno-record-gcc-switches -fno-common
archives:
- replacements:
    darwin: macOS
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '(?i)\breadme\b'
    - '(?i)\bsmall\b'
brews:
  -
    name: chippy
    github:
      owner: bradford-hamilton
      name: homebrew-chippy
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "https://github.com/bradford-hamilton/chippy"
    dependencies:
      - git
      - zsh
    install: |
      bin.install "chippy"
